# Datasource configuration in dev environment
spring:
  jpa:
    show-sql: false
    hibernate:
      default_schema: public
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    generate-ddl: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://db.xeuoorojivyeadjaxwam.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: px5TwhHa9A9feaio
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
server:
  port: 8090
